### ISSUE TITLE
Github Actions és build keretrendszer

### ISSUE THREAD

**Issue by kornellapu** [BME-MIT-IET/iet-hf-2023-zsivanyok2#2]
Continuous Integration (CI) fejlesztési módszerhez használt keretrendszer beüzelemése a Github Actions segítségével:
- Először az autómatikus buildelés beállítása, melynek célja, hogy commit után ellenőrzött körülmények között megtörténjen a program buildelése.
- A buildelést követően a program futtathatóságának ellenőrzése.
- Későbbiekben egyéb tesztek autómatikus futtatása.
- ( extra: más feladatok pl.: értesítő email küldése )

**Comment by kornellapu** [comment]
Sziasztok!

**Mi történt?**
Elkezdtem foglalkozni a Github Actions integrálásával, amit azzal kezdtem, klónoztam a repo-t.  
Utána feltettem a szükséges Node csomagokat az `npm install` parancsal VSCode terminálból indítva. Ez sikerült is hibátlanul.  
Majd el szerettem volna indítani, hogy a README.md-ben találtam a `ng serve` paranccsal, ez nem működött. *A csatolt képen ez látszik bal oldalon a terminálban.*  
Nem baj kicsit belenéztem a scriptekbe, ott a `ng serve` úgyis az `npm start`-ot hív, akkor én is azt meghívom, hogy futtassam.  Mint látható a képen hiba nélkül elindult az alkalmazás.  

**Amiben a segítség kell**
Egy olyan problémába ütköztem, amiről nem tudom, hogy hiba-e.
Szeretném megkérdezni @levente-murgas, hogy a csatolt képen látható hiba okoz-e problémát és ha igen akkor mi a teendő?  

**Kell-e nekem ezt a hibát javítani?**
Az oldal láthatóan fut, előtte bejelentkeztem a spotify fiókomba, ahogy azt az oldal kérte.  
Mivel csak a Github Actions a feladatom, ezért nekem a buildnek és "serve"-nek kell futnia. Ez meg is történt különben nem maga az oldal dobna hibát.  
*Nekem ez "runtime" hibának tűnik és ha jól gondolom az én feladatomat ez nem hátráltatja.*  

Előre is köszi a segítséget!
Kornél

![genrefy_runtime_error](https://github.com/BME-MIT-IET/iet-hf-2023-zsivanyok2/assets/36195679/30bbbe18-1b77-44f1-92c6-60c20c9f987c)

**Comment by levente-murgas** [comment]
Ha precízen nézzük a dolgokat akkor szerintem ez már valóban nem a te hatásköröd. A hibakódot elnézve a hibát egyébként az okozza, hogy nem volt sikeres a bejelentkezés utáni OAuth autentikáció. Persze más okai is lehetnek, több segítséget tudok nyújtani, ha a hibaüzenet body-jában lévő **message** mező értéket is elküldöd, ami több információval szolgál. Ezt Chrome böngészőn belül, az Inspect > Network fülén a megfelelő csomagot megkeresve a csomag "Response" részében tudod megtekinteni.

Egy lehetséges ok ami miatt nem sikerült az autentikáció:
A Spotify alkalmazáshoz hozzá kell rendelni a fejlesztői oldalon, hogy milyen más felhasználókat akarod, hogy legyen hozzáférése az fejlesztés alatt álló applikációhoz. Ehhez mindösszesen egy email címre van szükség, meg is adtam a tiedet is amit a csoportba küldtél, de most felmerült bennem az a sanda gyanú hogy, nem az @edu-s email címeddel vagy Spotify-ra regisztrálva. Amennyiben ez tényleg így van kérlek add, meg azt az email címed amivel Spotify-ra vagy regisztrálva.

**Comment by kornellapu** [comment]
Duplikált Issue.  
Másik Issue lesz megoldva: [itt](https://github.com/BME-MIT-IET/iet-hf-2023-zsivanyok2/issues/6 "Automatikus tesztelés és build keretrendszer").
