### ISSUE TITLE
UI tesztek

### ISSUE THREAD

**Issue by Marcell-Balint** [BME-MIT-IET/iet-hf-2023-zsivanyok2#4]
**A UI tesztelése selenium-al**

Ahogy az elmúlt két megbeszélésen megállapodtunk, a UI-t a selenium csomaggal teszteljük majd. 
A tesztelés során az alábbi feladatokat kell elvégezni:

/songs oldal 
 - Filteres gomb működésének tesztelése
 - Save playlist gomb működésének tesztelése

/filters oldal
- Show res tesztelése
- Clear all gomb tesztelése
- Műfajok automatikus tesztelése

Egyéb tesztek
- Oldalanként automatikusan tesztelni, hogy minden fontos HTML elem megjelenik-e
- Ha annyi filtert választasz hogy 0 dal matchel és át akarsz lépni a számokhoz akkor hibásan az összes dalt fogja mutatni -> teszt
  - Pl.: ID alapján

Egyéb feladatok
- Standard felhasználó létrehozása, hogy mindenki ugyan azzal a fiókkal tesztelhessen
- Felhasználó regisztrálása spotify-ra
- Spotify felhasználó regisztrálása az API-ba

**Comment by szullopeter** [comment]
Létrehoztam sikeresen a TesztUser-t, viszont új számok hozzáadásánál már a Bach után következő zeneszerzők nem jelennek meg, sem általuk újonnan hozott műfajok @levente-murgas Lehet, hogy egy korábbi verzió van fent, amiben ez probléma, vagy lehet hogy Vivaldi és Mozart nincsenek besorolva? A számok hozzáadóttak egyébként sikeresen. 
![image](https://github.com/BME-MIT-IET/iet-hf-2023-zsivanyok2/assets/100636268/8b36db1d-09e5-443a-b6e4-be79625ebe83)
 A képen látható artist-tömbben benne van Bach, viszont Vivaldi nincs, bár a jobb oldali listában megtalálható

**Comment by szullopeter** [comment]
Hozzáadtam a megfellő branchhez a szükséges UI-teszteket:
![teszteredmeny](https://github.com/BME-MIT-IET/iet-hf-2023-zsivanyok2/assets/100636268/9e18a14a-4bb3-4e81-90bf-a3ebb3425f19)
Annak érdekekében, hogy egységenként lehessen tesztelni az elemeket 11 tesztre bontottam.

**Comment by szullopeter** [comment]
@kornellapu A tesztek futtatásához a main.py-t lehetne futtatni esetleg az Actions-on, szükséges hozzá valami python package akkor az csak a pip install selenium csomag. Ha további kérdés van, vagy csomag probléma merülne fel, azt a dokumentációban jelöltem.

**Comment by kornellapu** [comment]
Rendben, viszont volna pár megjegyzésem.  

Először megnézem lokálisan, hogy tudom futtatni, ha ott működik, akkor utána felteszem az Actions-be.  

Az Actions-be felrakás viszont nem olyan egyszerű mert egy csupasz Ubuntunk van, amin a `pip` nem fog futni mivel az a telepített python csomaggal érkezik ha jól tudom, de  
találtam előre összerakott python-os Actions-t abból kiszedem ami nekünk kell.  

Actions-ben majd először le kell buildelni a python kódot a forrásfájlokból, ami azt jelenti, hogy nekem egy teljesen új python build-et kell készítenem a felhőben (különbözik a projekt Node-os buildelésétől). Így ez külön fog menni a project buildelésétől.  

Ha mindkettő build sikeresen lefutott utána tudjuk elindítani a Selenium tesztet és ellenőrizni annak eredményét.
Azt is meg kell néznem, hogy tudok ráellenőrizni majd, de először csak szépen sorban :D

**Comment by kornellapu** [comment]
+1 kérés ( @Marcell-Balint, @szullopeter ):
A feltöltött fájlok között van egy mappa: `genrefy_ui_tests\__pycache__`, ezt lehetne untrackelni és kitörölni a repoból, majd hozzáadni a .gitignore-hoz?

A kérés oka, az, hogy ezek bináris fájlok tehát a git borzalmasan kezeli és folyamatosan merge conflict-ot fog okozni.
Mivel nekem is le kell húzni a tesztekhez, ezért előfordulhat majd ilyen, mikor a `main`-be lesz mergelve.

**Comment by Marcell-Balint** [comment]
@kornellapu egyetértek a felvetéseddel, este nézzük át Petivel a branch-et, ott kitöröljük majd a cache-t és a main branch-re is rápusholok majd egy új .gitgnore-t.
