### ISSUE TITLE
Automatikus tesztelés és build keretrendszer

### ISSUE THREAD

**Issue by Marcell-Balint** [BME-MIT-IET/iet-hf-2023-zsivanyok2#6]
**Continuous Integration (CI**

Continuous Integration (CI) fejlesztési módszerhez használt keretrendszer beüzelemése a Github Actions segítségével:

- Automatikus buildelés beállítása
  - Commit után történjen meg a program buildelése
  - Érkezzen email
- Unit tesztek futtatása
  - Ha kész vannak a unit tesztek, akkor ezek is fussanak le automatikusan commit után
- UI tesztek futtatása
  - Ha kész vannak a UI tesztek, akkor ezek is fussanak le automatikusan commit után

**Comment by kornellapu** [comment]
Sziasztok!

Egy kisebb problémába ütköztem a Github Action-nél az **Ubuntu**n való teszteléskor.

@szullopeter a python teszt futtatásákor be van égetve egy `C:\Program Files (x86)\chromedrive.exe`, ami csak Windows platformon futtatható

<s>A képen látható, hogy Ubuntu-n futtatva a teszt nem indul el:</s>
***removed***

<s>Ez megoldható, hogy ne csak Windows-on működjön?  
Ha a script kaphatna egy paramétert, az sokban segítene, default-nak meg maradhatna a Windows-os path. </s>

Közben áttettem Ubunturól Windowsra a futtatott környezet így már elindul a teszt viszont a Selenium Webdriver kivételt dob...  
Próbálom megkeresni az okát, esetleg erre van valami tipped @szullopeter?
![image](https://github.com/BME-MIT-IET/iet-hf-2023-zsivanyok2/assets/36195679/16871d14-f454-4c58-8ccd-22d199521462)

Nagyon próbálkozom, de sajnos nem sok eredménnyel.  
Sehogy nem tudom rávenni a Selenium Python kódot, hogy fusson a platformokon, sajnos mindig elhasal a webdriver-nél:  
`net::ERR_CONNECTION_REFUSED` hibát dobva  

Máshogy is próbáltam és itt a `localhost` kifejezéssel lesz baj, viszont nem tudom, mire kéne átírni, hogy tudjon működni.
Ha IPv6-os címet használtam, azzal elindult de lokálisan tesztelve nem töltötte be a zenéket spotify-ról (csak Loading).
